version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.4.0
    steps:
    - checkout
    - run:
        name: install
        command: npm install
    - run:
        name: test & lint
        command: npm test && npm run lint
  deploy:
    docker:
      - image: circleci/node:8.4.0
    steps:
    - checkout
    - run:
        name: install
        command: npm install --no-save
    - run:
        name: login to npm
        command: |
            echo "$NPM_USERNAME\n$NPM_EMAIL"
            sh login.sh
    - run:
        name: setup git globals
        command: |
            git config --global push.default matching
            git config --global user.email "noreply@quran.com"
            git config --global user.name "circleci-qurandev"
    - run:
        name: patch update and commit package.json
        command: |
            echo "doing a patch update!"
            npm version patch
            git add .
            git commit --amend -m 'automated patching [ci skip]'
            git push
    - run:
        name: deploy to npm and gh
        command: |
            npm run deploy:npm
            npm run deploy:gp
workflows:
  version: 2
  test_and_build:
    jobs:
      - build
      - deploy:
          filters:
              branches:
                only: master
